#ifndef VIRTMACH_CODE_DSCAO__
#define VIRTMACH_CODE_DSCAO__
enum vcode {
	OP_NOP = 0x81, OP_CHECKSIG = 0xac, OP_EQUALVERIFY = 0x87,
	OP_DUP = 0x82, OP_POPDATA = 0x8d, OP_RIPEMD160 = 0xae,
	OP_CALCULATE_Y = 0x83, OP_BYTE2STR = 0x84
};
#endif /* VIRTMACH_CODE_DSCAO__ */
